live_config_reload = true

[bell]
animation = "Linear"
color = "#000000"
duration = 200

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
style.blinking = "On"
style.shape = "Underline"

[env]
TERM = "alacritty"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
padding.x = 5
padding.y = 5

### FONTS

[font]
size = 12
bold.family = "IosevkaNerdFont"
bold_italic.family = "IosevkaNerdFont"
italic.family = "IosevkaNerdFont"
normal.family = "IosevkaNerdFont"

### THEMES
[colors]
bright.black = "#475258"
bright.blue = "#7fbbb3"
bright.cyan = "#83c092"
bright.green = "#A7C080"
bright.magenta = "#d699b6"
bright.red = "#e67e80"
bright.white = "#d3c6aa"
bright.yellow = "#dbbc7f"

normal.black = "#d3c6aa"
normal.blue = "#7fbbb3"
normal.cyan = "#83c092"
normal.green = "#A7C080"
normal.magenta = "#d699b6"
normal.red = "#e67e80"
normal.white = "#d3c6aa"
normal.yellow = "#dbbc7f"

primary.background = "#272e33"
primary.foreground = "#d3c6aa"
