live_config_reload = true

[bell]
animation = "Linear"
color = "#000000"
duration = 200

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

#[shell]
#program = "/bin/bash"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.8

[window.padding]
x = 5
y = 5

### FONTS

[font]
size = 12

#[font.bold]
#family = "Iosevka"
#style = "Bold"
#
#[font.bold_italic]
#family = "Iosevka"
#style = "BoldItalic"

#[font.italic]
#family = "Iosevka"
#style = "Italic"

#[font.normal]
#family = "FiraCode"
#style = "Regular"

### THEMES

[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#d3c6aa"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#083b15"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"
