eval "$(starship init bash)"

if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
  source "$(fzf-share)/completion.bash"
fi

# Replace cd with zoxide
if command -v zoxide >/dev/null; then
  eval "$(zoxide init bash)"
  alias cd='z'
fi

# Replace ls with eza
if command -v eza >/dev/null; then
  alias ls='eza --icons'
fi

export PATH=$PATH:$HOME/go/bin

